"""Generated by Django 2.0.5 on 2020-03-15 19:18."""

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):
    """Will be used to create the tables during unittesting."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id',
                    models.AutoField(db_column='Id',
                                     primary_key=True,
                                     serialize=False)),
                ('created', models.DateTimeField(db_column='Created')),
                ('name', models.CharField(db_column='Name',
                                          max_length=45,
                                          unique=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': settings.IS_TESTING,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(db_column='Id',
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name',
                                          max_length=45, unique=True)),
                ['iso1', models.CharField(db_column='ISO1', max_length=45,
                                          blank=False, null=True)],
                ('added', models.DateTimeField(blank=True,
                                               db_column='Added', null=True)),
            ],
            options={
                'db_table': 'Language',
                'managed': settings.IS_TESTING,
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(db_column='Id',
                                        primary_key=True, serialize=False)),
                ('sentence', models.CharField(db_column='Sentence',
                                              max_length=255)),
                ('categoryid', models.IntegerField(db_column='CategoryId',
                                                   blank=False, null=False)),
                ('added', models.DateTimeField(db_column='Added')),
            ],
            options={
                'db_table': 'Sentence',
                'managed': settings.IS_TESTING,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(db_column='Id',
                                        primary_key=True, serialize=False)),
                ('added', models.DateTimeField(db_column='Added')),
                ('translation', models.CharField(db_column='Translation',
                                                 max_length=255)),
                ('languageid', models.IntegerField(db_column='LanguageId')),
                ('wordid', models.IntegerField(db_column='WordId',
                                               blank=True, null=True)),
                ('sentenceid', models.IntegerField(db_column='SentenceId',
                                                   blank=True, null=True))
            ],
            options={
                'db_table': 'Translation',
                'managed': settings.IS_TESTING,
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(db_column='Id',
                                        primary_key=True, serialize=False)),
                ('wordid', models.IntegerField(db_column='WordId')),
                ('pronouns', models.CharField(db_column='Pronouns',
                                              max_length=15)),
                ('verb', models.CharField(db_column='Verb', max_length=45)),
                ('tense', models.CharField(db_column='Tense', max_length=7)),
                ('added', models.DateTimeField(db_column='Added')),
            ],
            options={
                'db_table': 'Verb',
                'managed': settings.IS_TESTING,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(db_column='Id',
                                        primary_key=True, serialize=False)),
                ('word', models.CharField(db_column='Word',
                                          max_length=45, unique=True)),
                ('categoryid', models.IntegerField(db_column='CategoryId')),
                ('added', models.DateTimeField(db_column='Added')),
            ],
            options={
                'db_table': 'Word',
                'managed': settings.IS_TESTING,
            },
        ),
    ]
