# Generated by Django 2.0.5 on 2020-07-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formsubmits',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('formname', models.CharField(db_column='FormName', max_length=45)),
                ('companyname', models.CharField(blank=True, db_column='CompanyName', max_length=45, null=True)),
                ('customername', models.CharField(blank=True, db_column='CustomerName', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=45, null=True)),
                ('streetname', models.CharField(blank=True, db_column='Streetname', max_length=45, null=True)),
                ('housenumber', models.CharField(blank=True, db_column='Housenumber', max_length=45, null=True)),
                ('postcode', models.CharField(blank=True, db_column='Postcode', max_length=45, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('message', models.CharField(blank=True, db_column='Message', max_length=45, null=True)),
                ('submitted', models.DateTimeField(db_column='Submitted')),
                ('status', models.IntegerField(db_column='Status')),
            ],
            options={
                'db_table': 'FormSubmits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=45)),
                ('type', models.CharField(db_column='Type', max_length=15)),
                ('addbyuser', models.CharField(db_column='AddByUser', max_length=45)),
                ('added', models.DateTimeField(db_column='Added')),
                ('link', models.CharField(db_column='Link', max_length=255, unique=True)),
                ('socialmedianame', models.CharField(blank=True, db_column='SocialMediaName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Multimedia',
                'managed': False,
            },
        ),
    ]
