branch-defaults:
  master:
    environment: djange-env-staging
    group_suffix: null
global:
  application_name: fedal-api-staging
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
