branch-defaults:
  default:
    environment: api-staging2-dev
global:
  application_name: api-staging2
  branch: null
  default_ec2_keyname: aws_ssh
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
