branch-defaults:
  default:
    environment: api-staging
    group_suffix: null
global:
  application_name: fedal-api
  branch: null
  default_ec2_keyname: aws_ssh
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
