version: '3'

services:
    api:
        build: .
        # command: python api/manage.py runserver 0.0.0.0:8001
        # command: gunicorn --chdir api --bind :8001 api.wsgi:application
        # ports:
        #    - "8001:8001"
        volumes: 
            - .:/fedal_api
            - /static:/static
        networks:
            - nginx_network

    nginx:
        image: nginx:1.13
        ports:
            - "80:80"
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - /static:/static
        depends_on:
            - api
        networks:
            - nginx_network

networks:
    nginx_network:
        driver: bridge
